M48
; DRILL file {KiCad 8.0.6} date 2024-12-01T10:06:19+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-01T10:06:19+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X53.47Y14.425
X53.47Y9.575
T2
X56.5Y14.725
X56.5Y9.275
T3
X3.5Y26.5
X3.5Y3.5
X61.5Y26.5
X61.5Y3.5
M30
